[plugin]
repository = "https://github.com/Bluefissure/MapLinker.git"
commit = "e04647bd0f88cd91e05b97dda2d20dee7bec3b35"
owners = ["Bluefissure"]
project_path = "MapLinker"
changelog = "Patch 7.2 & API12"
